// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomMsg.proto

package com.fy.protobuf;

public final class CustomMessageData {
  private CustomMessageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 length = 1;</code>
     * @return The length.
     */
    long getLength();

    /**
     * <code>.MessageData.Content content = 2;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>.MessageData.Content content = 2;</code>
     * @return The content.
     */
    MessageData.Content getContent();
    /**
     * <code>.MessageData.Content content = 2;</code>
     */
    MessageData.ContentOrBuilder getContentOrBuilder();

    /**
     * <code>.MessageData.DataType order = 3;</code>
     * @return The enum numeric value on the wire for order.
     */
    int getOrderValue();
    /**
     * <code>.MessageData.DataType order = 3;</code>
     * @return The order.
     */
    MessageData.DataType getOrder();
  }
  /**
   * Protobuf type {@code MessageData}
   */
  public static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageData)
      MessageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      order_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              length_ = input.readInt64();
              break;
            }
            case 18: {
              Content.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(Content.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              order_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomMessageData.internal_static_MessageData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomMessageData.internal_static_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageData.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MessageData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *���ߵ�¼��֤���� �Ȼ�����Ϣ�ϱ�
       * </pre>
       *
       * <code>REQ_LOGIN = 0;</code>
       */
      REQ_LOGIN(0),
      /**
       * <pre>
       *�������ߵ�¼״̬�������Ϣ
       * </pre>
       *
       * <code>RSP_LOGIN = 1;</code>
       */
      RSP_LOGIN(1),
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PING = 2;</code>
       */
      PING(2),
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PONG = 3;</code>
       */
      PONG(3),
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>REQ_ACT = 4;</code>
       */
      REQ_ACT(4),
      /**
       * <pre>
       *������Ӧ
       * </pre>
       *
       * <code>RSP_ACT = 5;</code>
       */
      RSP_ACT(5),
      /**
       * <pre>
       *ָ������
       * </pre>
       *
       * <code>REQ_CMD = 6;</code>
       */
      REQ_CMD(6),
      /**
       * <pre>
       *ָ����Ӧ
       * </pre>
       *
       * <code>RSP_CMD = 7;</code>
       */
      RSP_CMD(7),
      /**
       * <pre>
       *��־����
       * </pre>
       *
       * <code>REQ_LOG = 8;</code>
       */
      REQ_LOG(8),
      /**
       * <pre>
       *��־��Ӧ
       * </pre>
       *
       * <code>RSP_LOG = 9;</code>
       */
      RSP_LOG(9),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *���ߵ�¼��֤���� �Ȼ�����Ϣ�ϱ�
       * </pre>
       *
       * <code>REQ_LOGIN = 0;</code>
       */
      public static final int REQ_LOGIN_VALUE = 0;
      /**
       * <pre>
       *�������ߵ�¼״̬�������Ϣ
       * </pre>
       *
       * <code>RSP_LOGIN = 1;</code>
       */
      public static final int RSP_LOGIN_VALUE = 1;
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PING = 2;</code>
       */
      public static final int PING_VALUE = 2;
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PONG = 3;</code>
       */
      public static final int PONG_VALUE = 3;
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>REQ_ACT = 4;</code>
       */
      public static final int REQ_ACT_VALUE = 4;
      /**
       * <pre>
       *������Ӧ
       * </pre>
       *
       * <code>RSP_ACT = 5;</code>
       */
      public static final int RSP_ACT_VALUE = 5;
      /**
       * <pre>
       *ָ������
       * </pre>
       *
       * <code>REQ_CMD = 6;</code>
       */
      public static final int REQ_CMD_VALUE = 6;
      /**
       * <pre>
       *ָ����Ӧ
       * </pre>
       *
       * <code>RSP_CMD = 7;</code>
       */
      public static final int RSP_CMD_VALUE = 7;
      /**
       * <pre>
       *��־����
       * </pre>
       *
       * <code>REQ_LOG = 8;</code>
       */
      public static final int REQ_LOG_VALUE = 8;
      /**
       * <pre>
       *��־��Ӧ
       * </pre>
       *
       * <code>RSP_LOG = 9;</code>
       */
      public static final int RSP_LOG_VALUE = 9;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return REQ_LOGIN;
          case 1: return RSP_LOGIN;
          case 2: return PING;
          case 3: return PONG;
          case 4: return REQ_ACT;
          case 5: return RSP_ACT;
          case 6: return REQ_CMD;
          case 7: return RSP_CMD;
          case 8: return REQ_LOG;
          case 9: return RSP_LOG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageData.DataType)
    }

    public interface ContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MessageData.Content)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 contentLength = 1;</code>
       * @return The contentLength.
       */
      long getContentLength();

      /**
       * <code>string data = 2;</code>
       * @return The data.
       */
      String getData();
      /**
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * Protobuf type {@code MessageData.Content}
     */
    public static final class Content extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MessageData.Content)
        ContentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Content.newBuilder() to construct.
      private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Content() {
        data_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new Content();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Content(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                contentLength_ = input.readInt64();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                data_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomMessageData.internal_static_MessageData_Content_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomMessageData.internal_static_MessageData_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Content.class, Builder.class);
      }

      public static final int CONTENTLENGTH_FIELD_NUMBER = 1;
      private long contentLength_;
      /**
       * <code>int64 contentLength = 1;</code>
       * @return The contentLength.
       */
      @Override
      public long getContentLength() {
        return contentLength_;
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private volatile Object data_;
      /**
       * <code>string data = 2;</code>
       * @return The data.
       */
      @Override
      public String getData() {
        Object ref = data_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        }
      }
      /**
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      @Override
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (contentLength_ != 0L) {
          output.writeInt64(1, contentLength_);
        }
        if (!getDataBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (contentLength_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, contentLength_);
        }
        if (!getDataBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Content)) {
          return super.equals(obj);
        }
        Content other = (Content) obj;

        if (getContentLength()
            != other.getContentLength()) return false;
        if (!getData()
            .equals(other.getData())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CONTENTLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getContentLength());
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Content parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Content parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Content parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Content parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Content parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Content parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Content parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Content parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Content parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Content parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Content parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Content parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Content prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MessageData.Content}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MessageData.Content)
          ContentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CustomMessageData.internal_static_MessageData_Content_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CustomMessageData.internal_static_MessageData_Content_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Content.class, Builder.class);
        }

        // Construct using com.fy.protobuf.CustomMessageData.MessageData.Content.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          contentLength_ = 0L;

          data_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CustomMessageData.internal_static_MessageData_Content_descriptor;
        }

        @Override
        public Content getDefaultInstanceForType() {
          return Content.getDefaultInstance();
        }

        @Override
        public Content build() {
          Content result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Content buildPartial() {
          Content result = new Content(this);
          result.contentLength_ = contentLength_;
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Content) {
            return mergeFrom((Content)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Content other) {
          if (other == Content.getDefaultInstance()) return this;
          if (other.getContentLength() != 0L) {
            setContentLength(other.getContentLength());
          }
          if (!other.getData().isEmpty()) {
            data_ = other.data_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Content parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Content) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long contentLength_ ;
        /**
         * <code>int64 contentLength = 1;</code>
         * @return The contentLength.
         */
        @Override
        public long getContentLength() {
          return contentLength_;
        }
        /**
         * <code>int64 contentLength = 1;</code>
         * @param value The contentLength to set.
         * @return This builder for chaining.
         */
        public Builder setContentLength(long value) {
          
          contentLength_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 contentLength = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearContentLength() {
          
          contentLength_ = 0L;
          onChanged();
          return this;
        }

        private Object data_ = "";
        /**
         * <code>string data = 2;</code>
         * @return The data.
         */
        public String getData() {
          Object ref = data_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            data_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string data = 2;</code>
         * @return The bytes for data.
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string data = 2;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string data = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <code>string data = 2;</code>
         * @param value The bytes for data to set.
         * @return This builder for chaining.
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          data_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MessageData.Content)
      }

      // @@protoc_insertion_point(class_scope:MessageData.Content)
      private static final Content DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Content();
      }

      public static Content getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Content>
          PARSER = new com.google.protobuf.AbstractParser<Content>() {
        @Override
        public Content parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Content(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Content> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Content> getParserForType() {
        return PARSER;
      }

      @Override
      public Content getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int LENGTH_FIELD_NUMBER = 1;
    private long length_;
    /**
     * <code>int64 length = 1;</code>
     * @return The length.
     */
    @Override
    public long getLength() {
      return length_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private Content content_;
    /**
     * <code>.MessageData.Content content = 2;</code>
     * @return Whether the content field is set.
     */
    @Override
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>.MessageData.Content content = 2;</code>
     * @return The content.
     */
    @Override
    public Content getContent() {
      return content_ == null ? Content.getDefaultInstance() : content_;
    }
    /**
     * <code>.MessageData.Content content = 2;</code>
     */
    @Override
    public ContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    public static final int ORDER_FIELD_NUMBER = 3;
    private int order_;
    /**
     * <code>.MessageData.DataType order = 3;</code>
     * @return The enum numeric value on the wire for order.
     */
    @Override public int getOrderValue() {
      return order_;
    }
    /**
     * <code>.MessageData.DataType order = 3;</code>
     * @return The order.
     */
    @Override public DataType getOrder() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(order_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0L) {
        output.writeInt64(1, length_);
      }
      if (content_ != null) {
        output.writeMessage(2, getContent());
      }
      if (order_ != DataType.REQ_LOGIN.getNumber()) {
        output.writeEnum(3, order_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, length_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContent());
      }
      if (order_ != DataType.REQ_LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, order_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageData)) {
        return super.equals(obj);
      }
      MessageData other = (MessageData) obj;

      if (getLength()
          != other.getLength()) return false;
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (order_ != other.order_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLength());
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + order_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageData)
        MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomMessageData.internal_static_MessageData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomMessageData.internal_static_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageData.class, Builder.class);
      }

      // Construct using com.fy.protobuf.CustomMessageData.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        length_ = 0L;

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        order_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomMessageData.internal_static_MessageData_descriptor;
      }

      @Override
      public MessageData getDefaultInstanceForType() {
        return MessageData.getDefaultInstance();
      }

      @Override
      public MessageData build() {
        MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageData buildPartial() {
        MessageData result = new MessageData(this);
        result.length_ = length_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.order_ = order_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageData) {
          return mergeFrom((MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageData other) {
        if (other == MessageData.getDefaultInstance()) return this;
        if (other.getLength() != 0L) {
          setLength(other.getLength());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.order_ != 0) {
          setOrderValue(other.getOrderValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long length_ ;
      /**
       * <code>int64 length = 1;</code>
       * @return The length.
       */
      @Override
      public long getLength() {
        return length_;
      }
      /**
       * <code>int64 length = 1;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(long value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 length = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        
        length_ = 0L;
        onChanged();
        return this;
      }

      private Content content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Content, Content.Builder, ContentOrBuilder> contentBuilder_;
      /**
       * <code>.MessageData.Content content = 2;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       * @return The content.
       */
      public Content getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? Content.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      public Builder setContent(Content value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      public Builder setContent(
          Content.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      public Builder mergeContent(Content value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              Content.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      public Content.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      public ContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              Content.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>.MessageData.Content content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Content, Content.Builder, ContentOrBuilder>
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Content, Content.Builder, ContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private int order_ = 0;
      /**
       * <code>.MessageData.DataType order = 3;</code>
       * @return The enum numeric value on the wire for order.
       */
      @Override public int getOrderValue() {
        return order_;
      }
      /**
       * <code>.MessageData.DataType order = 3;</code>
       * @param value The enum numeric value on the wire for order to set.
       * @return This builder for chaining.
       */
      public Builder setOrderValue(int value) {
        
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageData.DataType order = 3;</code>
       * @return The order.
       */
      @Override
      public DataType getOrder() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(order_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageData.DataType order = 3;</code>
       * @param value The order to set.
       * @return This builder for chaining.
       */
      public Builder setOrder(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        order_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageData.DataType order = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrder() {
        
        order_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageData)
    }

    // @@protoc_insertion_point(class_scope:MessageData)
    private static final MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageData();
    }

    public static MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      @Override
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageData_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageData_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017CustomMsg.proto\"\247\002\n\013MessageData\022\016\n\006len" +
      "gth\030\001 \001(\003\022%\n\007content\030\002 \001(\0132\024.MessageData" +
      ".Content\022$\n\005order\030\003 \001(\0162\025.MessageData.Da" +
      "taType\032.\n\007Content\022\025\n\rcontentLength\030\001 \001(\003" +
      "\022\014\n\004data\030\002 \001(\t\"\212\001\n\010DataType\022\r\n\tREQ_LOGIN" +
      "\020\000\022\r\n\tRSP_LOGIN\020\001\022\010\n\004PING\020\002\022\010\n\004PONG\020\003\022\013\n" +
      "\007REQ_ACT\020\004\022\013\n\007RSP_ACT\020\005\022\013\n\007REQ_CMD\020\006\022\013\n\007" +
      "RSP_CMD\020\007\022\013\n\007REQ_LOG\020\010\022\013\n\007RSP_LOG\020\tB$\n\017c" +
      "om.fy.protobufB\021CustomMessageDatab\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageData_descriptor,
        new String[] { "Length", "Content", "Order", });
    internal_static_MessageData_Content_descriptor =
      internal_static_MessageData_descriptor.getNestedTypes().get(0);
    internal_static_MessageData_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageData_Content_descriptor,
        new String[] { "ContentLength", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
